version: '3.7'

services:
  useful-db:
    container_name: postgres-useful
    image: postgres:12
    restart: on-failure
#    restart: always
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432
    volumes:
      - usefulpgdata:/var/lib/postgresql/data

  back:
    container_name: useful-back
    build:
      context: ./
      dockerfile: Dockerfile
      target: devstage
    env_file:
      - ./.env.dev
    command: uvicorn main:app --reload --port 5000 --host 0.0.0.0
    volumes:
      - .:/home/useful/app
    ports:
      - 8000:5000
    restart: always
    depends_on:
      - useful-db
#    command: /start-reload.sh
#    tty: true


volumes:
  usefulpgdata:

#networks:
#  default:
#    external:
#      name: useful-net
