version: '3.7'

services:
  db:
    container_name: useful-db
    image: postgres:12
    restart: always
#    env_file:
#      - ./.env.dev
    ports:
      - 5433:5432
    volumes:
      - usefulpgdata:/var/lib/postgresql/data

  back:
    container_name: useful-back
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    volumes:
      - ./:/app
    ports:
      - 8000:80
    restart: always
    depends_on:
      - db
    command: /start-reload.sh

volumes:
  usefulpgdata:
